name: earthquake_mapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1 # Sizin SDK versiyonunuz

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  flutter_riverpod: ^2.6.1 
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  riverpod_annotation: ^2.6.1
  geolocator: ^14.0.2
  intl: ^0.20.2
  webview_flutter: ^4.13.0
  firebase_core: ^4.0.0
  flutter_login: ^5.1.0
  firebase_auth: ^6.0.0
  fade_shimmer: ^2.4.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  persistent_bottom_nav_bar_v2: ^6.1.0
  font_awesome_flutter: ^10.8.0
  flutter_map_marker_cluster_plus: ^1.4.2
  logger: ^2.6.1
  cloud_firestore: ^6.0.0
  flutter_svg: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.5.4   
  riverpod_generator: ^2.6.5   
  riverpod_lint: ^2.6.5
  json_serializable: ^6.9.5


flutter:
  uses-material-design: true
  assets:
    - assets/icons/pin_logo.png
    - assets/icons/pin_logo_square.png
    - assets/icons/full_logo_horizontal.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/pin_logo_square.png"