// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRoxgJdvP8GQdiTeFxakHkkSJdi4Mra4A',
    appId: '1:1058778206904:web:1d7b3c7e522a52cd651a4d',
    messagingSenderId: '1058778206904',
    projectId: 'depremapp-1579c',
    authDomain: 'depremapp-1579c.firebaseapp.com',
    storageBucket: 'depremapp-1579c.firebasestorage.app',
    measurementId: 'G-95EGCE1207',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfBitmerrfNXwSWv3c2T1QyhCiVnfXS9s',
    appId: '1:1058778206904:android:43b7b6a349e03030651a4d',
    messagingSenderId: '1058778206904',
    projectId: 'depremapp-1579c',
    storageBucket: 'depremapp-1579c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXRy3FJvuepU3JazrrlAcIwCNZiOaxmRE',
    appId: '1:1058778206904:ios:9a025263b9b4b810651a4d',
    messagingSenderId: '1058778206904',
    projectId: 'depremapp-1579c',
    storageBucket: 'depremapp-1579c.firebasestorage.app',
    iosBundleId: 'com.example.earthquakeMapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXRy3FJvuepU3JazrrlAcIwCNZiOaxmRE',
    appId: '1:1058778206904:ios:9a025263b9b4b810651a4d',
    messagingSenderId: '1058778206904',
    projectId: 'depremapp-1579c',
    storageBucket: 'depremapp-1579c.firebasestorage.app',
    iosBundleId: 'com.example.earthquakeMapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRoxgJdvP8GQdiTeFxakHkkSJdi4Mra4A',
    appId: '1:1058778206904:web:61ffb5b848bc1dd2651a4d',
    messagingSenderId: '1058778206904',
    projectId: 'depremapp-1579c',
    authDomain: 'depremapp-1579c.firebaseapp.com',
    storageBucket: 'depremapp-1579c.firebasestorage.app',
    measurementId: 'G-KBYSBBKSH9',
  );
}
